dracut.install: fork, simplify and workaround zfs issues (2)
Signed-off-by: Nowa Ammerlaan <nowa@gentoo.org>

diff --git a/hooks/systemd/52-dracut.install b/hooks/systemd/52-dracut.install
--- a/hooks/systemd/52-dracut.install
+++ b/hooks/systemd/52-dracut.install
@@ -62,3 +62,21 @@ INITRAMFS_GEN_ARGS+=(
 )
 
 dracut "${INITRAMFS_GEN_ARGS[@]}" || exit 1
+
+# Fallback path for if we don't know if we generated an initramfs or
+# UKI. If dracut is used in uefi=yes mode, initrd will actually
+# be a combined kernel+initramfs UEFI executable. We can easily
+# recognize it by PE magic (vs cpio for a regular initramfs)
+if [[ ${IMAGE} == dracut-tmp ]]; then
+    read -rn 2 magic <"${KERNEL_INSTALL_STAGING_AREA}/${IMAGE}" ||
+        die "Cannot read ${KERNEL_INSTALL_STAGING_AREA}/${IMAGE}"
+    if [[ ${magic} == MZ ]]; then
+        einfo "Combined UEFI kernel+initramfs executable found"
+        mv "${KERNEL_INSTALL_STAGING_AREA}/${IMAGE}" \
+            "${KERNEL_INSTALL_STAGING_AREA}/uki.efi" || die "Failed to rename UKI"
+    else
+        einfo "Plain initramfs image found"
+        mv "${KERNEL_INSTALL_STAGING_AREA}/${IMAGE}" \
+            "${KERNEL_INSTALL_STAGING_AREA}/initrd" || die "Failed to rename initramfs"
+    fi
+fi
