91-grub-mkconfig.install: align +systemd with -systemd
grub-mkconfig should always exit non-fatally to ensure that
the whole emerge does not fail in containers where grub-mkconfig
might be unable to access the things it wants to access

See-also: https://github.com/projg2/installkernel-gentoo/pull/8
Signed-off-by: Andrew Ammerlaan <andrewammerlaan@gentoo.org>

diff --git a/hooks/systemd/91-grub-mkconfig.install b/hooks/systemd/91-grub-mkconfig.install
--- a/hooks/systemd/91-grub-mkconfig.install
+++ b/hooks/systemd/91-grub-mkconfig.install
@@ -61,5 +61,6 @@ if [[ ${COMMAND} == add || ${COMMAND} == remove ]]; then
 		"Generating new GRUB config as ${GRUB_CFG}"
 	dname="$(dirname "${GRUB_CFG}")"
 	mkdir -p "${dname}" || { echo "Failed to mkdir ${dname}" && exit 1; }
-	grub-mkconfig -o "${GRUB_CFG}" || { echo "grub-mkconfig failed" && exit 1; }
+	# Exit non-fatally to ensure emerge does not fail completely in containers
+	grub-mkconfig -o "${GRUB_CFG}" || { echo "grub-mkconfig failed" && exit 0; }
 fi
