installkernel: only install UKI in uki layout
and drop confusing -plain suffix

Signed-off-by: Andrew Ammerlaan <andrewammerlaan@gentoo.org>

diff --git a/hooks/systemd/95-efistub-kernel-bootcfg.install b/hooks/systemd/95-efistub-kernel-bootcfg.install
--- a/hooks/systemd/95-efistub-kernel-bootcfg.install
+++ b/hooks/systemd/95-efistub-kernel-bootcfg.install
@@ -18,7 +18,6 @@ else
 fi
 
 if [[ ${KERNEL_INSTALL_LAYOUT} == "uki" ]]; then
-	# UKI layout contains only UKIs
 	UKI="${KERNEL_INSTALL_BOOT_ROOT}/EFI/Linux/${KERNEL_INSTALL_ENTRY_TOKEN}-${KERNEL_VERSION}.efi"
 
 	if [[ ${COMMAND} == add ]]; then
@@ -41,79 +40,61 @@ if [[ ${KERNEL_INSTALL_LAYOUT} == "uki" ]]; then
 		kernel-bootcfg ${LOGLEVEL} --remove-uki "${UKI}" || exit 1
 	fi
 elif [[ ${KERNEL_INSTALL_LAYOUT} == "efistub"  ]]; then
-	KERNEL_IMAGE="${KERNEL_INSTALL_BOOT_ROOT}/EFI/Gentoo/kernel-${KERNEL_VERSION}-plain.efi"
-	UKI="${KERNEL_INSTALL_BOOT_ROOT}/EFI/Gentoo/kernel-${KERNEL_VERSION}.efi"
+	KERNEL_IMAGE="${KERNEL_INSTALL_BOOT_ROOT}/EFI/Gentoo/kernel-${KERNEL_VERSION}.efi"
 	INITRD="${KERNEL_INSTALL_BOOT_ROOT}/EFI/Gentoo/initramfs-${KERNEL_VERSION}.img"
 
 	if [[ ${COMMAND} == add ]]; then
+		if [[ -f ${KERNEL_IMAGE} ]]; then
+			echo "Kernel image not found, exiting"
+			exit 1
+		fi
+
 		KERNEL_BOOTCFG_ARGS=(
 			${LOGLEVEL}
 			--once
 		)
 
-		if [[ -f ${UKI} ]]; then
-			PARTLABEL="$(df ${UKI} --output=source | tail -1 | xargs -r lsblk --output=PARTLABEL --noheadings)"
-			if [[ -n ${PARTLABEL} ]]; then
-				TITLE="${KERNEL_VERSION} (UKI) on ${PARTLABEL}"
-			else
-				TITLE="${KERNEL_VERSION} (UKI)"
+		# From 90-loadentry.install
+		if [[ -n "${KERNEL_INSTALL_CONF_ROOT}" ]]; then
+			if [[ -f "${KERNEL_INSTALL_CONF_ROOT}/cmdline" ]]; then
+				BOOT_OPTIONS="$(tr -s "${IFS}" ' ' <"${KERNEL_INSTALL_CONF_ROOT}/cmdline")"
 			fi
-
-			KERNEL_BOOTCFG_ARGS+=(
-				--add-uki "${UKI}"
-				--title "${TITLE}"
-			)
-
-			[[ "${KERNEL_INSTALL_VERBOSE}" -gt 0 ]] && echo "Adding ${UKI} to UEFI boot entries"
-		elif [[ -f ${KERNEL_IMAGE} ]]; then
-			# From 90-loadentry.install
-			if [[ -n "${KERNEL_INSTALL_CONF_ROOT}" ]]; then
-				if [[ -f "${KERNEL_INSTALL_CONF_ROOT}/cmdline" ]]; then
-					BOOT_OPTIONS="$(tr -s "${IFS}" ' ' <"${KERNEL_INSTALL_CONF_ROOT}/cmdline")"
-				fi
-			elif [[ -f /etc/kernel/cmdline ]]; then
-				BOOT_OPTIONS="$(tr -s "${IFS}" ' ' </etc/kernel/cmdline)"
-			elif [[ -f /usr/lib/kernel/cmdline ]]; then
-				BOOT_OPTIONS="$(tr -s "${IFS}" ' ' </usr/lib/kernel/cmdline)"
-			else
-				BOOT_OPTIONS="$(tr -s "${IFS}" '\n' </proc/cmdline | grep -ve '^BOOT_IMAGE=' -e '^initrd=' | tr '\n' ' ')"
-			fi
-
-			# Append initramfs to cmdline if it exists
-			if [[ -f ${INITRD} ]]; then
-				INITRD_EFI_PATH="${INITRD#${KERNEL_INSTALL_BOOT_ROOT}}"
-				INITRD_EFI_PATH_DOS="${INITRD_EFI_PATH//\//\\}"
-				BOOT_OPTIONS="${BOOT_OPTIONS} initrd=${INITRD_EFI_PATH_DOS}"
-			fi
-
-			if [[ -n ${BOOT_OPTIONS} ]]; then
-				KERNEL_BOOTCFG_ARGS+=( --cmdline "${BOOT_OPTIONS}" )
-			fi
-
-			PARTLABEL="$(df ${KERNEL_IMAGE} --output=source | tail -1 | xargs -r lsblk --output=PARTLABEL --noheadings)"
-			if [[ -n ${PARTLABEL} ]]; then
-				TITLE="${KERNEL_VERSION} (plain) on ${PARTLABEL}"
-			else
-				TITLE="${KERNEL_VERSION} (plain)"
-			fi
-
-			KERNEL_BOOTCFG_ARGS+=(
-				--add-uki "${KERNEL_IMAGE}"
-				--title "${TITLE}"
-			)
-
-			[[ "${KERNEL_INSTALL_VERBOSE}" -gt 0 ]] && echo "Adding ${KERNEL_IMAGE} to UEFI boot entries with cmdline ${BOOT_OPTIONS}"
+		elif [[ -f /etc/kernel/cmdline ]]; then
+			BOOT_OPTIONS="$(tr -s "${IFS}" ' ' </etc/kernel/cmdline)"
+		elif [[ -f /usr/lib/kernel/cmdline ]]; then
+			BOOT_OPTIONS="$(tr -s "${IFS}" ' ' </usr/lib/kernel/cmdline)"
 		else
-			echo "No kernel image found, exiting"
-			exit 1
+			BOOT_OPTIONS="$(tr -s "${IFS}" '\n' </proc/cmdline | grep -ve '^BOOT_IMAGE=' -e '^initrd=' | tr '\n' ' ')"
 		fi
 
+		# Append initramfs to cmdline if it exists
+		if [[ -f ${INITRD} ]]; then
+			INITRD_EFI_PATH="${INITRD#${KERNEL_INSTALL_BOOT_ROOT}}"
+			INITRD_EFI_PATH_DOS="${INITRD_EFI_PATH//\//\\}"
+			BOOT_OPTIONS="${BOOT_OPTIONS} initrd=${INITRD_EFI_PATH_DOS}"
+		fi
+
+		if [[ -n ${BOOT_OPTIONS} ]]; then
+			KERNEL_BOOTCFG_ARGS+=( --cmdline "${BOOT_OPTIONS}" )
+		fi
+
+		PARTLABEL="$(df ${KERNEL_IMAGE} --output=source | tail -1 | xargs -r lsblk --output=PARTLABEL --noheadings)"
+		if [[ -n ${PARTLABEL} ]]; then
+			TITLE="${KERNEL_VERSION} (plain) on ${PARTLABEL}"
+		else
+			TITLE="${KERNEL_VERSION} (plain)"
+		fi
+
+		KERNEL_BOOTCFG_ARGS+=(
+			--add-uki "${KERNEL_IMAGE}"
+			--title "${TITLE}"
+		)
+
+		[[ "${KERNEL_INSTALL_VERBOSE}" -gt 0 ]] && echo "Adding ${KERNEL_IMAGE} to UEFI boot entries with cmdline ${BOOT_OPTIONS}"
 		kernel-bootcfg "${KERNEL_BOOTCFG_ARGS[@]}" || exit 1
 	elif [[ ${COMMAND} == remove ]]; then
-		[[ "${KERNEL_INSTALL_VERBOSE}" -gt 0 ]] && echo "Removing ${UKI} from UEFI boot entries"
-		kernel-bootcfg ${LOGLEVEL} --remove-uki "${UKI}"
 		[[ "${KERNEL_INSTALL_VERBOSE}" -gt 0 ]] && echo "Removing ${KERNEL_IMAGE} from UEFI boot entries"
-		kernel-bootcfg ${LOGLEVEL} --remove-uki "${KERNEL_IMAGE}"
+		kernel-bootcfg ${LOGLEVEL} --remove-uki "${KERNEL_IMAGE}" || exit 1
 	fi
 else
 	exit 0
