installkernel: localize some vars and return instead of exit on fail
Signed-off-by: Nowa Ammerlaan <nowa@gentoo.org>

diff --git a/installkernel b/installkernel
--- a/installkernel
+++ b/installkernel
@@ -133,7 +133,7 @@ dropindirs_sort() {
 
 # Create backups of older versions before installing
 updatever() {
-	oldsuffix="${3}.old"
+	local oldsuffix="${3}.old"
 	if [ "${3%.efi}" != "${3}" ]; then
 		# Some UEFIs enforce .efi suffix, so if using efi files retain suffix
 		oldsuffix="-old${3}"
@@ -173,29 +173,29 @@ updatever() {
 	fi
 }
 
+cleanup() {
+	# shellcheck disable=SC2317
+	if [ -n "${INSTALLKERNEL_STAGING_AREA}" ]; then
+		rm -rf "${INSTALLKERNEL_STAGING_AREA}"
+	fi
+}
+trap cleanup EXIT
+
 # Main installation script that we will call later
 main() {
-	ver=${1:?}
-	img=${2:?}
-	map=${3:?}
-	dir=${4:-/boot}
+	local ver=${1:?}
+	local img=${2:?}
+	local map=${3:?}
+	local dir=${4:-/boot}
 	if [ ${#} -gt 4 ]; then
 		echo "Too many arguments."
-		exit 1
+		return 1
 	fi
-
-	cleanup() {
-		# shellcheck disable=SC2317
-		if [ -n "${INSTALLKERNEL_STAGING_AREA}" ]; then
-			rm -rf "${INSTALLKERNEL_STAGING_AREA}"
-		fi
-	}
-	trap cleanup EXIT
 
 	INSTALLKERNEL_STAGING_AREA="$(mktemp -d -t installkernel.staging.XXXXXXX)"
 	export INSTALLKERNEL_STAGING_AREA
 
-	suffix=
+	local suffix= candidate=
 	if [ "${INSTALLKERNEL_LAYOUT}" = "efistub" ]; then
 		if [ ${#} -le 3 ] || [ "${4%/boot}" != "${4}" ]
 		then
@@ -254,12 +254,12 @@ main() {
 		fi
 	fi
 
-	base_dir=$(dirname "${img}")
-	prebuilt_initrd=${base_dir}/initrd
-	prebuilt_uki=${base_dir}/uki.efi
+	local base_dir=$(dirname "${img}")
+	local prebuilt_initrd=${base_dir}/initrd
+	local prebuilt_uki=${base_dir}/uki.efi
 
-	initrd=${INSTALLKERNEL_STAGING_AREA}/initrd
-	uki=${INSTALLKERNEL_STAGING_AREA}/uki.efi
+	local initrd=${INSTALLKERNEL_STAGING_AREA}/initrd
+	local uki=${INSTALLKERNEL_STAGING_AREA}/uki.efi
 
 	# Copy prebuilt initrd, uki.efi at kernel location
 	if [ -f "${prebuilt_initrd}" ]; then
@@ -274,7 +274,7 @@ main() {
 	# /usr/sbin and /sbin, just as dpkg would.
 	if [ ${#} -le 3 ] || [ "${4}" = "/boot" ]
 	then
-		err=0
+		local err=0
 		(
 			#shellcheck disable=SC2030
 			export LC_ALL=C PATH="${PATH}:/usr/sbin:/sbin"
@@ -301,14 +301,15 @@ main() {
 				fi
 			done
 		) || err=${?}
-		[ ${err} -eq 77 ] && exit 0
-		[ ${err} -ne 0 ] && exit ${err}
+		[ ${err} -eq 77 ] && return 0
+		[ ${err} -ne 0 ] && return ${err}
 	else
 		echo "WARNING: A custom installation directory is specified as fourth argument."
 		echo "WARNING: In this configuration running installation hooks is not supported."
 		echo "WARNING: All pre-installation hooks are ignored."
 	fi
 
+	local img_dest
 	if [ "${img%vmlinux*}" != "${img}" ]; then
 		img_dest=vmlinux
 	else
@@ -380,7 +381,7 @@ main() {
 		fi
 		updatever System.map "${map}"
 
-		basedir=$(dirname "${map}")
+		local basedir=$(dirname "${map}")
 		if [ -f "${basedir}/.config" ]; then
 			if [ "${INSTALLKERNEL_VERBOSE}" -gt 0 ]; then
 				echo "Installing config for ${ver}..."
@@ -399,7 +400,7 @@ main() {
 	# /usr/sbin and /sbin, just as dpkg would.
 	if [ ${#} -le 3 ] || [ "${4}" = "/boot" ]
 	then
-		err=0
+		local err=0
 		(
 			#shellcheck disable=SC2031
 			export LC_ALL=C PATH="${PATH}:/usr/sbin:/sbin"
@@ -426,15 +427,15 @@ main() {
 				fi
 			done
 		) || err=${?}
-		[ ${err} -eq 77 ] && exit 0
-		[ ${err} -ne 0 ] && exit ${err}
+		[ ${err} -eq 77 ] && return 0
+		[ ${err} -ne 0 ] && return ${err}
 	else
 		echo "WARNING: A custom installation directory is specified as fourth argument."
 		echo "WARNING: In this configuration running installation hooks is not supported."
 		echo "WARNING: All post-installation hooks are ignored."
 	fi
 
-	cleanup
+	return 0
 }
 
 # Find and read the install.conf
@@ -504,27 +505,31 @@ export ID="${ID:=linux}"
 export PRETTY_NAME="${PRETTY_NAME:=Linux}"
 
 # Now we actually run the install
+err=0
 if [ ${_ik_install_all} -eq 1 ]; then
 	for ver in /lib/modules/*; do
 		ver=$(basename "${ver}")
 		img=/lib/modules/${ver}/vmlinuz
 		map=/lib/modules/${ver}/System.map
 		if [ -f "${img}" ] && [ -f "${map}" ]; then
-			main "${ver}" "${img}" "${map}" "${_ik_arg_4}"
+			main "${ver}" "${img}" "${map}" "${_ik_arg_4}" ||
+				{ err=${?}; echo "WARNING: Installing ${ver} failed"; }
+			cleanup
 		else
 			if [ "${INSTALLKERNEL_VERBOSE}" -gt 0 ]; then
 				echo "WARNING: Skipping ${ver}, no kernel image or system map available."
 			fi
-			continue
 		fi
 	done
 else
 	if [ -f "${_ik_arg_2}" ] && [ -f "${_ik_arg_3}" ]; then
-		main "${_ik_arg_1}" "${_ik_arg_2}" "${_ik_arg_3}" "${_ik_arg_4}"
+		main "${_ik_arg_1}" "${_ik_arg_2}" "${_ik_arg_3}" "${_ik_arg_4}" ||
+			{ err=${?}; echo "ERROR: Installing ${_ik_arg_1} failed"; }
+		cleanup
 	else
 		echo "ERROR: No such kernel image or system map."
 		exit 1
 	fi
 fi
 
-exit 0
+exit ${err}
