hooks/50-dracut.install: fix read of tmp file, add missing die
This fixes installing UKIs when the install.conf is overridden
and initrd_generator/uki_generator are not set.

Closes: https://bugs.gentoo.org/930520
Signed-off-by: Andrew Ammerlaan <andrewammerlaan@gentoo.org>

diff --git a/hooks/50-dracut.install b/hooks/50-dracut.install
--- a/hooks/50-dracut.install
+++ b/hooks/50-dracut.install
@@ -70,10 +70,10 @@ main() {
 	# be a combined kernel+initramfs UEFI executable. We can easily
 	# recognize it by PE magic (vs cpio for a regular initramfs)
 	if [[ -s ${tmp} ]]; then
-		read -nr 2 magic <"${tmp}"
+		read -rn 2 magic <"${tmp}" || die "Cannot read ${tmp}"
 		if [[ ${magic} == MZ ]]; then
 			einfo "Combined UEFI kernel+initramfs executable found"
-			mv "${tmp}" "${uki}" || die "Failed to rename initramfs"
+			mv "${tmp}" "${uki}" || die "Failed to rename UKI"
 		else
 			einfo "Plain initramfs image found"
 			mv "${tmp}" "${initrd}" || die "Failed to rename initramfs"
