dracut.install: fork, simplify and workaround zfs issues
These fixes are stuck upstream for too long. I'm giving up and just
maintaining my own downstream fork of these scripts.

Signed-off-by: Nowa Ammerlaan <nowa@gentoo.org>

diff --git a/hooks/50-dracut.install b/hooks/50-dracut.install
--- a/hooks/50-dracut.install
+++ b/hooks/50-dracut.install
@@ -9,9 +9,6 @@
 ver=${1}
 img=${2}
 basedir=$(dirname "${img}")
-initrd=${INSTALLKERNEL_STAGING_AREA:-${basedir}}/initrd
-uki=${INSTALLKERNEL_STAGING_AREA:-${basedir}}/uki.efi
-tmp=${INSTALLKERNEL_STAGING_AREA:-${basedir}}/dracut-tmp
 
 # familiar helpers, we intentionally don't use Gentoo functions.sh
 die() {
@@ -42,8 +39,15 @@ main() {
 	# do nothing if somehow dracut is not installed
 	[[ -x $(command -v dracut) ]] || { ewarn "dracut is not installed, not generating an initramfs" && exit 0; }
 
+	# Skip kernel installation if zfs has not been built yet
+	if (grep ' / ' /proc/mounts | grep -q zfs) && ! modinfo zfs -k "${ver}" &>/dev/null
+	then
+		[[ ${INSTALLKERNEL_VERBOSE} == 1 ]] && ewarn \
+			"root is zfs, but the zfs module is missing, please build the zfs module and retry"
+		exit 77
+	fi
+
 	initramfs_gen_args=(
-		--add-confdir hostonly
 		# if uefi=yes is used, dracut needs to locate the kernel image
 		--kernel-image "${img}"
 	)
@@ -53,33 +57,27 @@ main() {
 	if [[ ${INSTALLKERNEL_UKI_GENERATOR} == dracut ]]; then
 		einfo "Using dracut as the initramfs and UKI generator..."
 		initramfs_gen_args+=( --uefi )
-		out="${uki}"
-		if [[ -f $(dirname "${img}")/uki.efi ]]; then
-			einfo "There is an UKI image at the same place as the kernel, skipping generating a new one"
-			cp --reflink=auto "$(dirname "${img}")/uki.efi" "${uki}" || die
-			chown root:root "${uki}" || die
-			chmod 0600 "${uki}" || die
-			exit 0
-		fi
+		out=uki.efi
 	elif [[ ${INSTALLKERNEL_INITRD_GENERATOR} == dracut ]]; then
 		einfo "Using dracut as the initramfs generator..."
 		initramfs_gen_args+=( --no-uefi )
-		out="${initrd}"
-		if [[ -f $(dirname "${img}")/initrd ]]; then
-			einfo "There is an initramfs image at the same place as the kernel, skipping generating a new one"
-			cp --reflink=auto "$(dirname "${img}")/initrd" "${initrd}" || die
-			chown root:root "${initrd}" || die
-			chmod 0600 "${initrd}" || die
-			exit 0
-		fi
+		out=initrd
 	else
 		einfo "No install.conf preference set, falling back to dracut.conf..."
-		out="${tmp}"
+		out=dracut-tmp
+	fi
+
+	if [[ -f ${basedir}/${out} ]]; then
+		einfo "There is an ${out} image at the same place as the kernel, skipping generating a new one"
+		cp --reflink=auto "${basedir}/${out}" "${INSTALLKERNEL_STAGING_AREA}/${out}" || die
+		chown root:root "${INSTALLKERNEL_STAGING_AREA}/${out}" || die
+		chmod 0600 "${INSTALLKERNEL_STAGING_AREA}/${out}" || die
+		exit 0
 	fi
 
 	initramfs_gen_args+=(
 		# positional arguments
-		"${out}" "${ver}"
+		"${INSTALLKERNEL_STAGING_AREA}/${out}" "${ver}"
 	)
 
 	dracut "${initramfs_gen_args[@]}" || die "Failed to generate initramfs"
@@ -88,14 +86,17 @@ main() {
 	# UKI. If dracut is used in uefi=yes mode, initrd will actually
 	# be a combined kernel+initramfs UEFI executable. We can easily
 	# recognize it by PE magic (vs cpio for a regular initramfs)
-	if [[ -s ${tmp} ]]; then
-		read -rn 2 magic <"${tmp}" || die "Cannot read ${tmp}"
+	if [[ ${out} == dracut-tmp ]]; then
+		read -rn 2 magic <"${INSTALLKERNEL_STAGING_AREA}/${out}" ||
+			die "Cannot read ${INSTALLKERNEL_STAGING_AREA}/${out}"
 		if [[ ${magic} == MZ ]]; then
 			einfo "Combined UEFI kernel+initramfs executable found"
-			mv "${tmp}" "${uki}" || die "Failed to rename UKI"
+			mv "${INSTALLKERNEL_STAGING_AREA}/dracut-tmp" \
+				"${INSTALLKERNEL_STAGING_AREA}/uki.efi" || die "Failed to rename UKI"
 		else
 			einfo "Plain initramfs image found"
-			mv "${tmp}" "${initrd}" || die "Failed to rename initramfs"
+			mv "${INSTALLKERNEL_STAGING_AREA}/dracut-tmp" \
+				"${INSTALLKERNEL_STAGING_AREA}/initrd" || die "Failed to rename initramfs"
 		fi
 	fi
 }
