*: shfmt and shellcheck
Signed-off-by: Andrew Ammerlaan <andrewammerlaan@gentoo.org>

diff --git a/hooks/90-uki-copy.install b/hooks/90-uki-copy.install
--- a/hooks/90-uki-copy.install
+++ b/hooks/90-uki-copy.install
@@ -30,12 +30,12 @@ main() {
 	# Use the same potential ESP mounting locations as eclean-kernel.
 	for dir in /boot/EFI /boot/efi /boot /efi; do
 		if [[ -d "${dir}/EFI/Linux" ]]; then
-				local image_path="${dir}/EFI/Linux/gentoo-$(basename ${img#*-})"
-				einfo "Installing UKI to ${image_path}"
-				if [[ -f "${image_path}" ]]; then
-					mv "${image_path}" "${image_path%.efi}-old.efi" || die "Failed to move existing UKI"
-				fi
-				mv "${img}" "${image_path}" || die "Failed to install UKI"
+			local image_path="${dir}/EFI/Linux/gentoo-$(basename ${img#*-})"
+			einfo "Installing UKI to ${image_path}"
+			if [[ -f ${image_path} ]]; then
+				mv "${image_path}" "${image_path%.efi}-old.efi" || die "Failed to move existing UKI"
+			fi
+			mv "${img}" "${image_path}" || die "Failed to install UKI"
 			break
 		else
 			continue
diff --git a/hooks/91-grub-mkconfig.install b/hooks/91-grub-mkconfig.install
--- a/hooks/91-grub-mkconfig.install
+++ b/hooks/91-grub-mkconfig.install
@@ -27,13 +27,13 @@ main() {
 	[[ -n ${NOCOLOR+yes} ]] && NOCOLOR=
 
 	# do nothing if somehow GRUB is not installed
-	[[ -x $(command -v grub-mkconfig) ]] || { ewarn "grub-mkconfig command not available" && exit 0 ; }
+	[[ -x $(command -v grub-mkconfig) ]] || { ewarn "grub-mkconfig command not available" && exit 0; }
 
 	[[ ${EUID} -eq 0 ]] || die "Please run this script as root"
 
 	if [[ -f ${GRUB_CFG} ]]; then
-        einfo "Backing up existing grub config as ${GRUB_CFG}~"
-        cp -v "${GRUB_CFG}"{,~} || die "Failed to save existing config"
+		einfo "Backing up existing grub config as ${GRUB_CFG}~"
+		cp -v "${GRUB_CFG}"{,~} || die "Failed to save existing config"
 	fi
 
 	einfo "Generating new GRUB config as ${GRUB_CFG}"
diff --git a/installkernel b/installkernel
--- a/installkernel
+++ b/installkernel
@@ -19,63 +19,63 @@ set -e
 # different, and passes in a fifth argument, just because it is
 # "special". We ignore the fifth argument, and do not flag is as an
 # error, which it would be for any arch apart from powerpc
-if [ $# -eq 3 ] || [ $# -eq 4 ] || [ $# -eq 5 ] ; then
-  img="$2"
-  map="$3"
-  ver="$1"
-  if [ $# -ge 4 ] && [ -n "$4" ] ; then
-      dir="$4"
-  else
-      dir="/boot"
-  fi
+if [ ${#} -eq 3 ] || [ ${#} -eq 4 ] || [ ${#} -eq 5 ]; then
+	img="${2}"
+	map="${3}"
+	ver="${1}"
+	if [ ${#} -ge 4 ] && [ -n "${4}" ]; then
+		dir="${4}"
+	else
+		dir="/boot"
+	fi
 else
-  echo "Usage: installkernel <version> <image> <System.map> <directory>"
-  exit 1
+	echo "Usage: installkernel <version> <image> <System.map> <directory>"
+	exit 1
 fi
 
 # Create backups of older versions before installing
-updatever () {
-  if [ -f "$dir/$1-$ver$3" ] ; then
-    # If they are hardlinked together, mv will fail.
-    rm -f "$dir/$1-$ver$3.old"
-    mv "$dir/$1-$ver$3" "$dir/$1-$ver$3.old"
-  fi
+updatever() {
+	if [ -f "${dir}/${1}-${ver}${3}" ]; then
+		# If they are hardlinked together, mv will fail.
+		rm -f "${dir}/${1}-${ver}${3}.old"
+		mv "${dir}/${1}-${ver}${3}" "${dir}/${1}-${ver}${3}.old"
+	fi
 
-  cat "$2" > "$dir/$1-$ver$3"
+	cat "${2}" >"${dir}/${1}-${ver}${3}"
 
-  # This section is for backwards compatibility only
-  if test -f "$dir/$1$3" || test -L "$dir/$1$3" ; then
-    # The presence of "$dir/$1$3" is unusual in modern installations, and
-    # the results are mostly unused.  So only recreate them if they
-    # already existed.
-    if test -L "$dir/$1$3" ; then
-        # If we were using links, continue to use links, updating if
-        # we need to.
-        if [ "$(readlink -f "${dir}/${1}$3")" = "${dir}/${1}-${ver}$3" ]; then
-            # Yup, we need to change
-            ln -sf "$1-$ver$3.old" "$dir/$1$3.old"
-        else
-            # If they are hardlinked together, mv will fail.
-            rm -f "$dir/$1$3.old"
-            mv "$dir/$1$3" "$dir/$1$3.old"
-        fi
-        ln -sf "$1-$ver$3" "$dir/$1$3"
-    else                        # No links
-        # If they are hardlinked together, mv will fail.
-        rm -f "$dir/$1$3.old"
-        mv "$dir/$1$3" "$dir/$1$3.old"
-        cat "$2" > "$dir/$1$3"
-    fi
-  fi
+	# This section is for backwards compatibility only
+	if test -f "${dir}/${1}${3}" || test -L "${dir}/${1}${3}"; then
+		# The presence of "${dir}/${1}${3}" is unusual in modern installations, and
+		# the results are mostly unused.  So only recreate them if they
+		# already existed.
+		if test -L "${dir}/${1}${3}"; then
+			# If we were using links, continue to use links, updating if
+			# we need to.
+			if [ "$(readlink -f "${dir}/${1}${3}")" = "${dir}/${1}-${ver}${3}" ]; then
+				# Yup, we need to change
+				ln -sf "${1}-${ver}${3}.old" "${dir}/${1}${3}.old"
+			else
+				# If they are hardlinked together, mv will fail.
+				rm -f "${dir}/${1}${3}.old"
+				mv "${dir}/${1}${3}" "${dir}/${1}${3}.old"
+			fi
+			ln -sf "${1}-${ver}${3}" "${dir}/${1}${3}"
+		else # No links
+			# If they are hardlinked together, mv will fail.
+			rm -f "${dir}/${1}${3}.old"
+			mv "${dir}/${1}${3}" "${dir}/${1}${3}.old"
+			cat "${2}" >"${dir}/${1}${3}"
+		fi
+	fi
 }
 
 # If installing in the usual directory, run the same scripts that hook
 # into kernel package installation.  Also make sure the PATH includes
 # /usr/sbin and /sbin, just as dpkg would.
 if [ "${dir}" = "/boot" ]; then
-  PATH="${PATH}:/usr/sbin:/sbin" \
-    run-parts --verbose --exit-on-error --arg="${ver}" --arg="${img}" \
-    /etc/kernel/preinst.d
+	PATH="${PATH}:/usr/sbin:/sbin" \
+		run-parts --verbose --exit-on-error --arg="${ver}" --arg="${img}" \
+		/etc/kernel/preinst.d
 fi
 
 # use the same input path as /usr/lib/kernel/install.d/50-dracut.install
@@ -84,39 +84,39 @@ base_dir=$(dirname "${img}")
 initrd=${base_dir}/initrd
 uki=${base_dir}/uki.efi
 
-if [ "$(basename "$img")" = "vmlinux" ] ; then
-  img_dest=vmlinux
+if [ "$(basename "${img}")" = "vmlinux" ]; then
+	img_dest=vmlinux
 else
-  img_dest=vmlinuz
+	img_dest=vmlinuz
 fi
 
 # If we found a uki.efi, install it instead of kernel+initrd
-if [ -f ${uki} ]; then
-  suffix=.efi
-  updatever ${img_dest} "${uki}" ${suffix}
+if [ -f "${uki}" ]; then
+	suffix=.efi
+	updatever ${img_dest} "${uki}" ${suffix}
 else
-  suffix=
-  updatever ${img_dest} "${img}"
-  if [ -f "${initrd}" ] ; then
-    updatever initramfs "${initrd}" .img
-  fi
+	suffix=
+	updatever ${img_dest} "${img}"
+	if [ -f "${initrd}" ]; then
+		updatever initramfs "${initrd}" .img
+	fi
 fi
 
 updatever System.map "${map}"
 
 config=$(dirname "${map}")
 config="${config}/.config"
-if [ -f "${config}" ] ; then
-  updatever config "${config}"
+if [ -f "${config}" ]; then
+	updatever config "${config}"
 fi
 
 # If installing in the usual directory, run the same scripts that hook
 # into kernel package installation.  Also make sure the PATH includes
 # /usr/sbin and /sbin, just as dpkg would.
 if [ "${dir}" = "/boot" ]; then
-  PATH="${PATH}:/usr/sbin:/sbin" \
-    run-parts --verbose --exit-on-error --arg="${ver}" --arg="${dir}/${img_dest}-${ver}${suffix}" \
-    /etc/kernel/postinst.d
+	PATH="${PATH}:/usr/sbin:/sbin" \
+		run-parts --verbose --exit-on-error --arg="${ver}" --arg="${dir}/${img_dest}-${ver}${suffix}" \
+		/etc/kernel/postinst.d
 fi
 
 exit 0
