hooks/91-grub-mkconfig.install: Fixed capitalization of Gentoo and GRUB
Signed-off-by: Jaak Ristioja <jaak@ristioja.ee>

diff --git a/hooks/91-grub-mkconfig.install b/hooks/91-grub-mkconfig.install
--- a/hooks/91-grub-mkconfig.install
+++ b/hooks/91-grub-mkconfig.install
@@ -4,7 +4,7 @@
 
 : "${GRUB_CFG:=/boot/grub/grub.cfg}"
 
-# familiar helpers, we intentionally don't use gentoo functions.sh
+# familiar helpers, we intentionally don't use Gentoo functions.sh
 die() {
 	echo -e " ${NOCOLOR-\e[1;31m*\e[0m }${*}" >&2
 	exit 1
@@ -18,20 +18,20 @@ main() {
 	# re-define for subst to work
 	[[ -n ${NOCOLOR+yes} ]] && NOCOLOR=
 
-	# do nothing if somehow grub is not installed
+	# do nothing if somehow GRUB is not installed
 	[[ -x $(command -v grub-mkconfig) ]] || exit 0
 
 	[[ ${EUID} -eq 0 ]] || die "Please run this script as root"
 
 	if [[ -f ${GRUB_CFG} ]]; then
-		einfo "Backing up existing grub config as ${GRUB_CFG}~"
+		einfo "Backing up existing GRUB config as ${GRUB_CFG}~"
 		cp -v "${GRUB_CFG}"{,~} || die "Failed to save existing config"
 	fi
 
-	einfo "Generating new grub config as ${GRUB_CFG}"
+	einfo "Generating new GRUB config as ${GRUB_CFG}"
 	local dname="${GRUB_CFG%/*}"
 	mkdir -vp "${dname}" || die "Failed to mkdir ${dname}"
-	grub-mkconfig -o "${GRUB_CFG}" || die "Failed to generate grub config"
+	grub-mkconfig -o "${GRUB_CFG}" || die "Failed to generate GRUB config"
 }
 
 main
