*/*: unify options for the copy command
In general we want to preserve everything and always follow symlinks.

Signed-off-by: Nowa Ammerlaan <nowa@gentoo.org>

diff --git a/hooks/91-grub-mkconfig.install b/hooks/91-grub-mkconfig.install
--- a/hooks/91-grub-mkconfig.install
+++ b/hooks/91-grub-mkconfig.install
@@ -38,7 +38,7 @@ main() {
 
 	if [[ -f ${GRUB_CFG} ]]; then
 		einfo "Backing up existing grub config as ${GRUB_CFG}~..."
-		cp -v "${GRUB_CFG}"{,~} || die "Failed to save existing config"
+		cp --dereference --preserve=all "${GRUB_CFG}"{,~} || die "Failed to save existing config"
 	fi
 
 	if [[ -f /etc/os-release ]]; then
diff --git a/hooks/95-refind-copy-icon.install b/hooks/95-refind-copy-icon.install
--- a/hooks/95-refind-copy-icon.install
+++ b/hooks/95-refind-copy-icon.install
@@ -48,7 +48,7 @@ main() {
 	if [[ -f ${icon} ]]; then
 		mv "${icon}" "${icon_old}" || die
 	fi
-	cp "${REFIND_ICON}" "${icon}" || die "Failed to copy icon file"
+	cp --dereference --preserve=all "${REFIND_ICON}" "${icon}" || die "Failed to copy icon file"
 
 	# If there is a version-less image, install an icon for it
 	local icon_nover=${icon//-${ver}/}
@@ -67,11 +67,11 @@ main() {
 		ln -sf "$(basename "${icon}")" "${icon_nover}" || die
 	elif [[ -f ${icon_nover} ]]; then
 		mv "${icon_nover}" "${icon_nover_old}" || die
-		cp "${icon}" "${icon_nover}" || die
+		cp --dereference --preserve=all "${icon}" "${icon_nover}" || die
 	elif [[ -L ${img//-${ver}/} ]]; then
 		ln -sf "$(basename "${icon}")" "${icon_nover}" || die
 	elif [[ -f ${img//-${ver}/} ]]; then
-		cp "${icon}" "${icon_nover}" || die
+		cp --dereference --preserve=all "${icon}" "${icon_nover}" || die
 	fi
 }
 
diff --git a/hooks/systemd/91-grub-mkconfig.install b/hooks/systemd/91-grub-mkconfig.install
--- a/hooks/systemd/91-grub-mkconfig.install
+++ b/hooks/systemd/91-grub-mkconfig.install
@@ -73,7 +73,7 @@ if [[ ${COMMAND} == add || ${COMMAND} == remove ]]; then
 	if [[ -f ${GRUB_CFG} ]]; then
 		[[ ${KERNEL_INSTALL_VERBOSE} == 1 ]] && echo \
 			"Backing up existing grub config as ${GRUB_CFG}~"
-		cp "${GRUB_CFG}"{,~} || { echo "Failed to save existing config" && exit 1; }
+		cp --dereference --preserve=all "${GRUB_CFG}"{,~} || { echo "Failed to save existing config" && exit 1; }
 	fi
 
 	[[ ${KERNEL_INSTALL_VERBOSE} == 1 ]] && echo \
