95-refind-copy-icon.install: also copy icon in efistub layout
Signed-off-by: Andrew Ammerlaan <andrewammerlaan@gentoo.org>

diff --git a/hooks/95-refind-copy-icon.install b/hooks/95-refind-copy-icon.install
--- a/hooks/95-refind-copy-icon.install
+++ b/hooks/95-refind-copy-icon.install
@@ -24,9 +24,7 @@ main() {
 
 	[[ ${EUID} -eq 0 ]] || die "Please run this script as root"
 
-	if [[ ${INSTALLKERNEL_LAYOUT} == compat || ${INSTALLKERNEL_LAYOUT} == uki ]]; then
-		cp "${REFIND_ICON}" "${img%.efi}.png" || die "Failed to copy icon file"
-	fi
+	cp "${REFIND_ICON}" "${img%.efi}.png" || die "Failed to copy icon file"
 }
 
 main
