*: use install instead of cp when installing to possible FAT location
cp --preserve was a mistake. The proper solution to the problem
raised in projg2/installkernel-gentoo/pull/32 is to umask the
entire partition in fstab. This is also recommended by systemd, and
tools such as bootctl will complain if this is not the case. Instead
of using cp, we use install, and we use it in the exact same way that
the hooks that ship with systemd use it for consistency. Blindly
preserving the original mode was never a good idea because we cannot
know what the original mode is. Dracut may explicitly umask it to 077
but this is no guarantee for other initramfs generators. And also, if
the original file was not owned by root we will create all sorts of
weirdness trying to preserve that on a FAT file system. So partially
revert 04f43c7c06c30bf5a3ffd723c9b7bd72879552c0 and
aad29bd40ae0de81760b300840dc28b851683a5b and just do what systemd does
instead. We can keep the --preserve stuff when copying in the same
directory (such as backing up grub.cfg), or when writing to the
staging area.

See-also: https://github.com/projg2/installkernel-gentoo/pull/32
Closes: https://github.com/projg2/installkernel-gentoo/issues/34
Signed-off-by: Nowa Ammerlaan <nowa@gentoo.org>

diff --git a/hooks/95-refind-copy-icon.install b/hooks/95-refind-copy-icon.install
--- a/hooks/95-refind-copy-icon.install
+++ b/hooks/95-refind-copy-icon.install
@@ -31,8 +31,6 @@ main() {
 	# re-define for subst to work
 	[[ -n ${NOCOLOR+yes} ]] && NOCOLOR=
 
-	[[ ${EUID} -eq 0 ]] || die "Please run this script as root"
-
 	if [[ ! -f ${REFIND_ICON} ]]; then
 		die "REFIND_ICON=${REFIND_ICON} not found"
 	fi
@@ -48,7 +46,7 @@ main() {
 	if [[ -f ${icon} ]]; then
 		mv "${icon}" "${icon_old}" || die
 	fi
-	cp --dereference --preserve=all "${REFIND_ICON}" "${icon}" || die "Failed to copy icon file"
+	install -m 0644 "${REFIND_ICON}" "${icon}" || die "Failed to copy icon file"
 
 	# If there is a version-less image, install an icon for it
 	local icon_nover=${icon//-${ver}/}
@@ -67,11 +65,11 @@ main() {
 		ln -sf "$(basename "${icon}")" "${icon_nover}" || die
 	elif [[ -f ${icon_nover} ]]; then
 		mv "${icon_nover}" "${icon_nover_old}" || die
-		cp --dereference --preserve=all "${icon}" "${icon_nover}" || die
+		install -m 0644 "${icon}" "${icon_nover}" || die
 	elif [[ -L ${img//-${ver}/} ]]; then
 		ln -sf "$(basename "${icon}")" "${icon_nover}" || die
 	elif [[ -f ${img//-${ver}/} ]]; then
-		cp --dereference --preserve=all "${icon}" "${icon_nover}" || die
+		install -m 0644 "${icon}" "${icon_nover}" || die
 	fi
 }
 
